default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: proyecto_final_development

test:
  <<: *default
  database: proyecto_final_test

production:
  <<: *default
  host: localhost
  database: proyecto_final_production
  username: proyecto_final
  password: <%= ENV['PROYECTO_FINAL_DATABASE_PASSWORD'] %>
